name: CI

on: [ push,  pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tpak
            asset_name: tpak_linux
          - os: macos-latest
            artifact_name: tpak
            asset_name: tpak_macos
          - os: windows-latest
            artifact_name: tpak.exe
            asset_name: tpak.exe

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.1
      with:
        action: build
    - name: Move artifacts
      shell: bash
      run: |
        mkdir -p artifacts
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp build/tpak.exe artifacts
        else
          cp build/tpak artifacts
        fi
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.os }}
        path: artifacts
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: continous
        overwrite: true
